steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/uniqravi/${_REPO_NM}']
  id: 'check-out-source-code'
- name: python:3.7
  entrypoint: pip
  args: ["install", "-r", "requirements.txt",'--user']
  dir: '${_REPO_NM}/source-code/data-processing-code/'
  id: 'install dependencies'
- name: python:3.7
  entrypoint: python
  args: ['-m','${_PYTHON_DATA_PIPELINE_FILE_NM}','--runner','DataflowRunner','--project','${_PROJECT_NM}','--staging_location',
         '${_DATAFLOW_STAGE_LOCATION}','--temp_location','${_DATAFLOW_TEMP_LOCATION}',
           '--template_location','${_DATAFLOW_TEMPLATE_LOCATION}','--region','${_REGION_NM}']
  dir: '${_REPO_NM}/source-code/data-processing-code/'
  id: 'create ${_DATAFLOW_TEMPLATE_FILE_NM} template'
- name: gcr.io/cloud-builders/gsutil
  args: ['cp','${_DATAFLOW_TEMPLATE_FILE_NM}_metadata','${_DATAFLOW_TEMPLATE_DIR}/template/']
  dir: '${_REPO_NM}/source-code/data-processing-code/'
- name: gcr.io/cloud-builders/gcloud
  args: ['functions','deploy','${_CLOUD_FUNCTION_NM}','--project','${_PROJECT_NM}','--region','${_REGION_NM}','--runtime=python37','--entry-point',
         'temp_trigger_etl_flow','--set-env-vars PROJECT_NM=${_PROJECT_NM},TEMPLATE_LOC=${_DATAFLOW_TEMPLATE_LOCATION},TEMP_LOC=${_DATAFLOW_TEMP_LOCATION},LOCATION=${_REGION_NM},ETL_NM=${_PIPELINE_TITLE}',
         '--trigger-resource','${_BUCKET_SOURCE_NM}','--trigger-event','google.storage.object.finalize']
  dir: '${_REPO_NM}/source-code/cloud-functions/'
  id: 'deploy cloud function'
logsBucket: 'gs://gcp_etl_project/buildlogs'
options:
  logging: GCS_ONLY
  dynamic_substitutions: true
substitutions:
  _PIPELINE_TITLE : GCP_ORDER_ETL
  _REPO_NM : CI-CD-Python-Order-ETL #default value
  _PROJECT_NM : gcp-learning-333002
  _PYTHON_DATA_PIPELINE_FILE_NM : gcp_dataflow_pipeline
  _DATAFLOW_TEMPLATE_DIR : gs://gcp_etl_project/dataflow_templates/order
  _DATAFLOW_TEMPLATE_FILE_NM : GCP_ORDER_ETL
  _DATAFLOW_STAGE_LOCATION: ${_DATAFLOW_TEMPLATE_DIR}/staging
  _DATAFLOW_TEMP_LOCATION: ${_DATAFLOW_TEMPLATE_DIR}/temp
  _DATAFLOW_TEMPLATE_LOCATION : ${_DATAFLOW_TEMPLATE_DIR}/template/${_DATAFLOW_TEMPLATE_FILE_NM}
  _REGION_NM : us-west1
  _CLOUD_FUNCTION_NM : trigger_etl_cloud_fn
  _BUCKET_SOURCE_NM : gs://olist_order_bucket_etl


  #name: gcr.io/cloud-builders/gsutil
  #args: ['cp', '-r','GCP_ETL_Project/source-code/data-processing-code','gs://gcp_etl_project/code']
  #dir: 'GCP_ETL_Project/source-code/data-processing-code'
  #id: 'copy-pipeline-code'
  #name: gcr.io/cloud-builders/gsutil
  #args: ['cp', '-r','GCP_ETL_Project/source-code/data-processing-code/','gs://gcp_etl_project/code']
  #dir: 'GCP_ETL_Project/source-code/data-processing-code'
  #id: 'copy-pipeline-code'




